<span style='font-size:50px; font-weight:bold;'>Data Cleaning and Preprocessing</span>

---

In [5]:
# import basic libraries
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("data/IMDb_movies_new_data.csv")
df.head()

,title,genres,description,keywords,release_date,duration,content_rating,director,star_1,star_2,...,metascore,votes,user_reviews,critic_reviews,watchlist_count,gross,budget,opening_weekend,movie_url,category
0,Kate &amp; Leopold,Comedy|Fantasy|Romance,An English Duke from 1876 is inadvertently dra...,"time travel,time travel romance,female time tr...",2001-12-25,118,PG-13,James Mangold,Meg Ryan,Hugh Jackman,...,44.0,93728,376,92,66.6K,"$76,019,048","$48,000,000 (estimated)","$9,725,408",https://www.imdb.com/title/tt0035423/,Mid Rated
1,Ko to tamo peva,Adventure|Comedy|Drama,"It&apos;s April 5, 1941, somewhere in Serbia. ...","road trip,sex scene,female nudity,year 1941,yu...",1980-06-30,86,NaN,Slobodan Sijan,Pavle Vuisic,Dragan Nikolic,...,NaN,17866,42,11,12.2K,NaN,NaN,NaN,https://www.imdb.com/title/tt0076276/,Top Rated|Old Movies
2,Cannibal Holocaust,Adventure|Horror,An anthropologist ventures into the Amazon rai...,"rape,animal cruelty,gang rape,actual animal ki...",1985-06-21,95,Unrated,Ruggero Deodato,Robert Kerman,Francesca Ciardi,...,22.0,66614,685,208,66.8K,$477,"$100,000 (estimated)",NaN,https://www.imdb.com/title/tt0078935/,Old Movies
3,Saturn 3,Adventure|Horror|Sci-Fi,Two lovers stationed at a remote base in the a...,"psychopath,infatuation,robot sci fi,male rear ...",1980-02-15,88,R,Stanley Donen,Farrah Fawcett,Kirk Douglas,...,9.0,11548,165,63,9.3K,"$9,000,000","£10,000,000 (estimated)",NaN,https://www.imdb.com/title/tt0079285/,Old Movies
4,Moskva slezam ne verit,Comedy|Drama|Romance,Three young provincial women come to Moscow in...,"city name in title,group of friends,soviet uni...",1980-02-11,150,PG,Vladimir Menshov,Vera Alentova,Aleksey Batalov,...,NaN,15658,56,13,14.6K,$217,"$900,000 (estimated)",NaN,https://www.imdb.com/title/tt0079579/,Old Movies

In [4]:
df[df['title'].str.contains('Titanic')]

,title,genres,description,keywords,release_date,duration,content_rating,director,star_1,star_2,...,metascore,votes,user_reviews,critic_reviews,watchlist_count,gross,budget,opening_weekend,movie_url,category
1438,Titanic - La leggenda continua,Animation|Family|Fantasy,A Cinderella meets her Prince Charming on the ...,"rapping,sinking ship,ship,titanic,flashback wi...",2000-09-15,90,Not Rated,Camillo Teti,Lisa Russo,Mark Thompson-Ashworth,...,NaN,9795,94,10,3.6K,NaN,NaN,NaN,https://www.imdb.com/title/tt0330994/,Low Rated
3697,Titanic 666,Horror|Thriller,"Dark forces from the deep rise to the surface,...","supernatural thriller,tubi original,titanic,gh...",2022-04-15,91,TV-MA,Nick Lyon,Keesha Sharp,Jamie Bamber,...,NaN,4731,50,12,2.5K,"$214,456",NaN,NaN,https://www.imdb.com/title/tt18394428/,Low Rated

In [6]:
df.shape

(5645, 24)

---

# Handling Duplicates

<span style='font-size:18px;'>
    ➤ Duplicate entries were identified using the unique movie URL <br>
    ➤ Each movie was retained as a single record
</span>

In [7]:
dup_url = df['movie_url'].duplicated().sum()
print("Total Duplicate URL Rows: ",dup_url)

Total Duplicate URL Rows:  9

In [8]:
df = df.drop_duplicates(subset=['movie_url'])

In [9]:
df.shape

(5636, 24)

---

# Handling Missing Values

<span style='font-size:18px;'>
Missing values were handled based on the importance of each feature and the proportion of missing data. Before deciding we’ll check the percentage (%) of the missing values for each column: <br><br>

**Rule**: <br>
➤ < 20% missing → **Keep** <br>
➤ 20–40% → **Use carefully** <br>
➤ 40% & above → **Drop Column based on feature importance** <br>
</span>

In [10]:
df.isna().sum()

title                 0
genres                7
description           6
keywords            164
release_date         76
duration              0
content_rating     1010
director              2
star_1                6
star_2               35
star_3               47
countries             0
languages            42
rating                0
metascore          1988
votes                 0
user_reviews        109
critic_reviews      450
watchlist_count     623
gross              1390
budget             1784
opening_weekend    2227
movie_url             0
category              0
dtype: int64

In [11]:
df.isna().mean() * 100

title               0.000000
genres              0.124202
description         0.106458
keywords            2.909865
release_date        1.348474
duration            0.000000
content_rating     17.920511
director            0.035486
star_1              0.106458
star_2              0.621008
star_3              0.833925
countries           0.000000
languages           0.745209
rating              0.000000
metascore          35.273243
votes               0.000000
user_reviews        1.933996
critic_reviews      7.984386
watchlist_count    11.053939
gross              24.662881
budget             31.653655
opening_weekend    39.513840
movie_url           0.000000
category            0.000000
dtype: float64

---

## I. Genres

<span style='font-size:18px;'>
➤ A small portion of records had missing genres due to incomplete information about genres on the movie page. <br>

➤ Missing entries were replaced with **"Unknown"**
</span>

In [46]:
df['genres'] = df['genres'].fillna('Unknown')

In [47]:
df['genres'].isna().sum()

np.int64(0)

---

# II. Description

<span style='font-size:18px;'>
➤ A small portion of records had missing description due to incomplete information about it on the movie page. <br>

➤ Missing entries were replaced with **"No Description available"**
</span>

In [48]:
df['description'] = df['description'].fillna("No description available")

In [49]:
df['description'].isna().sum()

np.int64(0)

---

# III. Keywords

<span style='font-size:18px;'>
➤ A small portion of records had missing keywords due to incomplete information about it on the movie page. <br>

➤ Missing entries were replaced with **"empty string"**.
</span>

In [50]:
df['keywords'] = df['keywords'].fillna("")

In [51]:
df['keywords'].isna().sum()

np.int64(0)

---

## IV. Release Date

<span style='font-size:18px;'>
➤ A small portion of records had missing release dates due to incomplete JSON data. However, month and year information was available on the webpage. <br><br>
    
➤ Missing entries were re-scraped from the source <br>

➤ The first day of the respective month was assigned **(i.e., day=1)** <br>

➤ Default date was assigned as **‘2000-01-01’** for null records even after re-scraping. We got 7 records out of 5649, so replaced by default.
</span>

In [52]:
df['release_date'].isna().sum()

np.int64(76)

In [53]:
missing_df = df[df['release_date'].isna()]
missing_df

,title,genres,description,keywords,release_date,duration,content_rating,director,star_1,star_2,...,metascore,votes,user_reviews,critic_reviews,watchlist_count,gross,budget,opening_weekend,movie_url,category
261,Nostalghia,Drama,A Russian poet and his interpreter travel to I...,"italy,church,candle,snowing,disillusionment",NaN,125,Not Rated,Andrei Tarkovsky,Oleg Yankovskiy,Erland Josephson,...,74.0,32942,97,56,82.2K,"$328,196",NaN,"$11,537",https://www.imdb.com/title/tt0086022/,Old Movies
328,Tsisperi mtebi anu daujerebeli ambavi,Comedy|Drama,An author - a passive young man - enters the S...,"caucasus,georgia europe,language,collapse,comm...",NaN,97,NaN,Eldar Shengelaia,Ramaz Giorgobiani,Vasil Kakhniashvili,...,NaN,2539,11,5,3.5K,NaN,NaN,NaN,https://www.imdb.com/title/tt0087349/,Top Rated
416,Ghoulies,Comedy|Fantasy|Horror,A young man and his girlfriend move into his p...,"supernatural power,levitation,strangulation,fi...",NaN,81,PG-13,Luca Bercovici,Peter Liapis,Lisa Pelikan,...,26.0,11473,108,98,8.3K,NaN,"$5,500,000 (estimated)",NaN,https://www.imdb.com/title/tt0089200/,Old Movies
465,Shoah,Documentary|History|War,Claude Lanzmann&apos;s epic documentary recoun...,"holocaust,shoah,witness,testimony,genocide",NaN,566,Not Rated,Claude Lanzmann,Simon Srebnik,Michael Podchlebnik,...,99.0,11543,69,55,45.1K,"$20,175",NaN,"$2,874",https://www.imdb.com/title/tt0090015/,Old Movies|Top Rated
477,The Toxic Avenger,Action|Comedy|Horror,Tromaville has a monstrous new hero. The Toxic...,"superhero,absurd violence,absurdism,gore,mutation",NaN,82,R,Michael Herz,Andree Maranda,Mitch Cohen,...,42.0,37043,220,150,25.0K,NaN,"$475,000 (estimated)",NaN,https://www.imdb.com/title/tt0090190/,Old Movies
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5013,The Amityville Terror,Horror,When a new family moves to an old house in Ami...,"brother sister relationship,psychotronic film,...",NaN,84,Not Rated,Michael Angelo,Nicole Tompkins,Kaiwi Lyman,...,NaN,1382,36,21,1.9K,NaN,"$500,000 (estimated)",NaN,https://www.imdb.com/title/tt5312612/,Low Rated
5051,Life Begins Now,Drama|Romance,"A celebration of life, a glance into death, an...",life,NaN,84,NaN,Fabiano Albuquerque,Leah Egan,Fergus Keane,...,NaN,2239,8,NaN,NaN,NaN,NaN,NaN,https://www.imdb.com/title/tt5552086/,Top Rated
5054,Much Ado About Nothing,Comedy|Romance,"Young lovers Hero and Claudio, soon to wed, co...","cool,sexual tension,double marriage,half broth...",NaN,161,NaN,Robert Delamere,Jonathan Coy,Leo Staar,...,NaN,1335,8,NaN,9.7K,NaN,NaN,NaN,https://www.imdb.com/title/tt5569310/,Top Rated
5422,Bros. Last Call,Comedy,Comedy Matt is facing the inevitable ending of...,friend,NaN,92,NaN,Don Tjernagel,Matt Lee Ingebritson,Rory Even,...,NaN,3524,NaN,NaN,NaN,NaN,"$5,000 (estimated)",NaN,https://www.imdb.com/title/tt8018008/,Low Rated
5504,Kiss the Ground,Documentary,"A revolutionary group of activists, scientists...","water,soil,farmer,environment,regenerative far...",NaN,84,PG,Joshua Tickell,Woody Harrelson,Ray Archuleta,...,NaN,8108,458,11,13.2K,NaN,NaN,NaN,https://www.imdb.com/title/tt8618654/,Top Rated

In [7]:
from datetime import datetime

# converting to date from the month and year
def create_date(month, year):
    try:
        return datetime.strptime(f"1 {month} {year}", "%d %B %Y").date()
    except:
        return None

In [8]:
import re, time, random
from bs4 import BeautifulSoup

# Getting month and year from the movie page
def scrape_month_year(driver, url):
    driver.get(url)
    
    time.sleep(random.uniform(3, 5))
    
    soup = BeautifulSoup(driver.page_source, "html.parser")

    try:
        block = soup.find("div", {"data-testid": "title-details-section"})
        date_text = block.select_one('[data-testid="title-details-releasedate"] div').text.strip()
    except:
        date_text = '2000-01-01'

    match = re.match(r'(.*\d).*', date_text)

    try:
        month, year = match.group(1).split(' ')
    except:
        year = match.group(1)
        month = 'January'
        
    return month, year

In [56]:
from IMDB_Scraping import get_driver

driver = get_driver()
count = 1

# Re-scraping and replacing null dates
for idx, row in missing_df.iterrows():
    url = row['movie_url']
    print(f"Re-Scraping: {count}/{len(missing_df)}")
    month, year = scrape_month_year(driver, url)
    df.loc[idx, "release_date"] = create_date(month, year)

    time.sleep(random.uniform(2,4))
    count += 1

driver.quit()

Re-Scraping: 1/76
Re-Scraping: 2/76
Re-Scraping: 3/76
Re-Scraping: 4/76
Re-Scraping: 5/76
Re-Scraping: 6/76
Re-Scraping: 7/76
Re-Scraping: 8/76
Re-Scraping: 9/76
Re-Scraping: 10/76
Re-Scraping: 11/76
Re-Scraping: 12/76
Re-Scraping: 13/76
Re-Scraping: 14/76
Re-Scraping: 15/76
Re-Scraping: 16/76
Re-Scraping: 17/76
Re-Scraping: 18/76
Re-Scraping: 19/76
Re-Scraping: 20/76
Re-Scraping: 21/76
Re-Scraping: 22/76
Re-Scraping: 23/76
Re-Scraping: 24/76
Re-Scraping: 25/76
Re-Scraping: 26/76
Re-Scraping: 27/76
Re-Scraping: 28/76
Re-Scraping: 29/76
Re-Scraping: 30/76
Re-Scraping: 31/76
Re-Scraping: 32/76
Re-Scraping: 33/76
Re-Scraping: 34/76
Re-Scraping: 35/76
Re-Scraping: 36/76
Re-Scraping: 37/76
Re-Scraping: 38/76
Re-Scraping: 39/76
Re-Scraping: 40/76
Re-Scraping: 41/76
Re-Scraping: 42/76
Re-Scraping: 43/76
Re-Scraping: 44/76
Re-Scraping: 45/76
Re-Scraping: 46/76
Re-Scraping: 47/76
Re-Scraping: 48/76
Re-Scraping: 49/76
Re-Scraping: 50/76
Re-Scraping: 51/76
Re-Scraping: 52/76
Re-Scraping: 53/76
Re-Scraping: 54/76
Re-Scraping: 55/76
Re-Scraping: 56/76
Re-Scraping: 57/76
Re-Scraping: 58/76
Re-Scraping: 59/76
Re-Scraping: 60/76
Re-Scraping: 61/76
Re-Scraping: 62/76
Re-Scraping: 63/76
Re-Scraping: 64/76
Re-Scraping: 65/76
Re-Scraping: 66/76
Re-Scraping: 67/76
Re-Scraping: 68/76
Re-Scraping: 69/76
Re-Scraping: 70/76
Re-Scraping: 71/76
Re-Scraping: 72/76
Re-Scraping: 73/76
Re-Scraping: 74/76
Re-Scraping: 75/76
Re-Scraping: 76/76

In [57]:
df['release_date'].isna().sum()

np.int64(7)

In [58]:
df['release_date'] = df['release_date'].fillna('2000-01-01')

In [59]:
df["release_date"] = pd.to_datetime(df["release_date"], errors="coerce")

In [60]:
df['release_date'].dtype

dtype('<M8[ns]')

In [61]:
df['release_date'].isna().sum()

np.int64(0)

---

## V. Content Rating

<span style='font-size:18px;'>Approximately **~18% of missing values** were observed in the content rating  column due to incomplete information about content rating on the movie page. <br>
➤ Missing entries were replaced with **"Unknown"**
</span>

In [62]:
df['content_rating'].unique()

array(['PG-13', nan, 'Unrated', 'R', 'PG', 'Not Rated', 'G', 'TV-MA',
       'NC-17', 'TV-PG', 'TV-14', '16+', 'X', '13+', 'TV-G', 'Approved',
       'TV-Y7', '18+', 'TV-13'], dtype=object)

In [63]:
df['content_rating'] = df['content_rating'].fillna('Unknown')

In [64]:
df['content_rating'].isna().sum()

np.int64(0)

---

## VI. Stars, Directors, & Languages

<span style='font-size:18px;'>Less than **1% of missing values** were observed in the star_1, star_2, star_3, and director, and langauges columns due to incomplete information about stars and director on the movie page.<br>
➤ Missing entries were replaced with **"Unknown"**
</span>

In [65]:
df['star_1'] = df['star_1'].fillna('Unknown')
df['star_2'] = df['star_2'].fillna('Unknown')
df['star_3'] = df['star_3'].fillna('Unknown')
df['director'] = df['director'].fillna('Unknown')
df['languages'] = df['languages'].fillna("Unknown")

In [66]:
df[['star_1', 'star_2', 'star_3', 'director', 'languages']].isna().sum()

star_1       0
star_2       0
star_3       0
director     0
languages    0
dtype: int64

In [67]:
df.isna().sum()

title                 0
genres                0
description           0
keywords              0
release_date          0
duration              0
content_rating        0
director              0
star_1                0
star_2                0
star_3                0
countries             0
languages             0
rating                0
metascore          1988
votes                 0
user_reviews        109
critic_reviews      450
watchlist_count     623
gross              1390
budget             1784
opening_weekend    2227
movie_url             0
category              0
dtype: int64

---

# VII. Watchlist Count, User Reviews, & Critic Reviews

<span style='font-size:18px;'>
➤ A small portion of records had missing values in watchlist_count, user_reviews, and critic_reviews due to incomplete information about it on the movie page. <br>

➤ Missing entries were replaced with **'0'**, because as it was not present which means no one had given the reviews nor added to the watchlist. <br>
➤ Values in **'K'** and **'M'** are converted into numeric form (1000s and 1000000s).
</span>

In [9]:
def convert_to_number(x):
    if pd.isna(x):
        return 0

    if isinstance(x, (int, float)):
        return x
    
    x = str(x).replace(',', '').strip().upper()
    
    if 'K' in x:
        return float(x.replace('K', '')) * 1_000
    elif 'M' in x:
        return float(x.replace('M', '')) * 1_000_000
    else:
        return float(x)

In [133]:
df['watchlist_count'] = df['watchlist_count'].apply(convert_to_number)
df['user_reviews'] = df['user_reviews'].apply(convert_to_number)
df['critic_reviews'] = df['critic_reviews'].apply(convert_to_number)

In [134]:
df[['user_reviews', 'critic_reviews', 'watchlist_count']].isna().sum()

user_reviews       0
critic_reviews     0
watchlist_count    0
dtype: int64

In [135]:
df[['title', 'user_reviews','critic_reviews','watchlist_count']].head()

                    title  user_reviews  critic_reviews  watchlist_count
0          Kate & Leopold         376.0            92.0          66600.0
1         Ko to tamo peva          42.0            11.0          12200.0
2      Cannibal Holocaust         685.0           208.0          66800.0
3                Saturn 3         165.0            63.0           9300.0
4  Moskva slezam ne verit          56.0            13.0          14600.0

---

# Currency Conversion

In [70]:
df['budget'] = df['budget'].astype(str)
df['gross'] = df['gross'].astype(str)

In [10]:
import re

def extract_currency_type(x):
    if pd.isnull(x):
        return None
    
    # Extract currency prefix (before numbers)
    match = re.match(r"[^\d]+", x)
    return match.group().strip() if match else None


df["currency_type"] = df["budget"].apply(extract_currency_type)

In [72]:
df['currency_type'].unique()

array(['$', 'nan', '£', 'A$', 'CA$', 'ITL', 'DEM', 'FRF', '¥', 'SEK',
       'NZ$', '₹', '€', 'TRL', 'ATS', 'PLN', 'R$', 'CN¥', '₩', 'EGP',
       'RON', 'RUR', 'SAR', 'IRR', 'BDT', 'NOK', 'NT$', 'HUF', 'DKK',
       'MX$', 'NPR', 'PKR', 'ZAR', 'LKR', 'IDR', 'MVR'], dtype=object)

In [11]:
conversion_rates = {
    "$": 1.0,        # USD
    "£": 1.25,       # GBP
    "€": 1.10,       # Euro
    "¥": 0.007,      # Japanese Yen
    "CN¥": 0.14,     # Chinese Yuan
    "₹": 0.012,      # Indian Rupee
    "A$": 0.65,      # Australian Dollar
    "CA$": 0.75,     # Canadian Dollar
    "NZ$": 0.60,     # New Zealand Dollar
    "R$": 0.20,      # Brazilian Real
    "MX$": 0.058,    # Mexican Peso
    "NT$": 0.031,    # Taiwan Dollar
    "₩": 0.00075,    # South Korean Won
    "SEK": 0.095,    # Swedish Krona
    "NOK": 0.095,    # Norwegian Krone
    "DKK": 0.15,     # Danish Krone
    "PLN": 0.25,     # Polish Zloty
    "HUF": 0.0028,   # Hungarian Forint
    "RON": 0.22,     # Romanian Leu
    "ZAR": 0.055,    # South African Rand
    "SAR": 0.27,     # Saudi Riyal
    "EGP": 0.032,    # Egyptian Pound
    "PKR": 0.0036,   # Pakistani Rupee
    "BDT": 0.0091,   # Bangladeshi Taka
    "NPR": 0.0075,   # Nepali Rupee
    "LKR": 0.0031,   # Sri Lankan Rupee
    "IDR": 0.000065, # Indonesian Rupiah
    "MVR": 0.065,    # Maldivian Rufiyaa

    # Old currencies (approx historical conversion)
    "ITL": 0.00055,  # Italian Lira
    "FRF": 0.18,     # French Franc
    "DEM": 0.55,     # German Mark
    "TRL": 0.000000035, # Old Turkish Lira
    "ATS": 0.073,    # Austrian Schilling
    "RUR": 0.013,    # Old Russian Ruble

    # Missing / unknown
    "nan": None
}

In [12]:
def extract_currency_amount(x):
    if pd.isnull(x):
        return None, None
    
    currency = re.match(r"[^\d]+", x)
    currency = currency.group().strip() if currency else None
    
    amount = re.findall(r"[\d,]+", x)
    amount = int(amount[0].replace(",", "")) if amount else None
    
    return currency, amount

In [13]:
def convert_to_usd(x):
    currency, amount = extract_currency_amount(x)
    
    if currency in conversion_rates and amount:
        rate = conversion_rates[currency]
        if rate:
            return amount * rate
    
    return None

In [76]:
df['gross_usd'] = df['gross'].apply(convert_to_usd)
df["budget_usd"] = df["budget"].apply(convert_to_usd)

In [77]:
df[['title', 'gross', 'gross_usd', 'budget', 'budget_usd']]

,title,gross,gross_usd,budget,budget_usd
0,Kate &amp; Leopold,"$76,019,048",76019048.0,"$48,000,000 (estimated)",48000000.0
1,Ko to tamo peva,nan,NaN,nan,NaN
2,Cannibal Holocaust,$477,477.0,"$100,000 (estimated)",100000.0
3,Saturn 3,"$9,000,000",9000000.0,"£10,000,000 (estimated)",12500000.0
4,Moskva slezam ne verit,$217,217.0,"$900,000 (estimated)",900000.0
...,...,...,...,...,...
5640,Bandit,"$467,005",467005.0,nan,NaN
5641,Holidate,nan,NaN,nan,NaN
5642,Seishun buta yaro wa yumemiru shoujo no yume w...,"$3,060,705",3060705.0,nan,NaN
5643,I Care a Lot,"$1,351,662",1351662.0,"$14,000,000 (estimated)",14000000.0
5644,Kaithi,"$522,938",522938.0,"₹240,000,000 (estimated)",2880000.0

In [78]:
df[['gross_usd', 'budget_usd']].isna().mean() * 100

gross_usd     24.662881
budget_usd    31.706884
dtype: float64

## Handling Missing Values in Gross and Budget

<span style='font-size:18px;'>The gross column had approximately **25% missing values**. <br>
The budget column had approximately **30% missing values** <br>
➤ Both columns were cleaned and converted into numeric format by converting the currency to US Dollar. <br>
➤ Missing values were retained as null (NaN) to avoid introducing bias.
</span>

In [79]:
df[['gross_usd', 'budget_usd']].dtypes

gross_usd     float64
budget_usd    float64
dtype: object

---

## VI. Opening Weekend

<span style='font-size:18px;'>The opening_weekend column had approximately **40% missing values**.
Additionally, it was not directly aligned with the project’s focus on ratings and audience behavior. <br>
➤ We'll **remove this column** from the dataset.
</span>

In [80]:
# Dropping opening_weekend columns
df = df.drop(columns=["opening_weekend"])

In [81]:
df.isna().sum()

title                 0
genres                0
description           0
keywords              0
release_date          0
duration              0
content_rating        0
director              0
star_1                0
star_2                0
star_3                0
countries             0
languages             0
rating                0
metascore          1988
votes                 0
user_reviews          0
critic_reviews        0
watchlist_count       0
gross                 0
budget                0
movie_url             0
category              0
currency_type         0
gross_usd          1390
budget_usd         1787
dtype: int64

In [82]:
# Checking datatypes of all columns
df.dtypes

title                      object
genres                     object
description                object
keywords                   object
release_date       datetime64[ns]
duration                    int64
content_rating             object
director                   object
star_1                     object
star_2                     object
star_3                     object
countries                  object
languages                  object
rating                    float64
metascore                 float64
votes                       int64
user_reviews               object
critic_reviews             object
watchlist_count            object
gross                      object
budget                     object
movie_url                  object
category                   object
currency_type              object
gross_usd                 float64
budget_usd                float64
dtype: object

---

## Text Cleaning and Starndardization

<span style='font-size:18px;'>
Text-based columns such as title, genres, content_rating, stars, and directors were cleaned by: <br>

➤ Removing extra spaces.<br>
➤ Standardized formatting. <br>
➤ Title, Stars, and Director columns contains HTML encoded characters such as `&amp;`, `&apos;`, and `&quot;`, these characters are: 
<br>
&emsp; • `&apm;` → & <br>
&emsp; • `&apos;` → ' <br>
&emsp; • `&quot;` → " <br><br>
➤ Using `unescape()` function of html module we can convert the all HTML entities.
</span>

In [83]:
df[df['title'].str.contains(";")].head()

,title,genres,description,keywords,release_date,duration,content_rating,director,star_1,star_2,...,user_reviews,critic_reviews,watchlist_count,gross,budget,movie_url,category,currency_type,gross_usd,budget_usd
0,Kate &amp; Leopold,Comedy|Fantasy|Romance,An English Duke from 1876 is inadvertently dra...,"time travel,time travel romance,female time tr...",2001-12-25,118,PG-13,James Mangold,Meg Ryan,Hugh Jackman,...,376,92,66.6K,"$76,019,048","$48,000,000 (estimated)",https://www.imdb.com/title/tt0035423/,Mid Rated,$,76019048.0,48000000.0
6,&apos;Breaker&apos; Morant,Drama|History|War,Three Australian lieutenants are court martial...,"based on true story,1900s,19th century,boer,co...",1980-07-03,107,PG,Bruce Beresford,Edward Woodward,Jack Thompson,...,119,69,15.7K,$948,"A$800,000 (estimated)",https://www.imdb.com/title/tt0080310/,Old Movies,A$,948.0,520000.0
25,Cheech and Chong&apos;s Next Movie,Comedy|Crime,Cheech and Chong live in a decrepit old house ...,"cheech and chong,best friend,police officer,fl...",1980-07-18,99,R,Tommy Chong,Cheech Marin,Tommy Chong,...,51,26,11.6K,"$41,675,194",nan,https://www.imdb.com/title/tt0080520/,Old Movies,nan,41675194.0,NaN
26,Coal Miner&apos;s Daughter,Biography|Drama|Music,"The fictionalized life of singer Loretta Lynn,...","country music,kentucky,singer,1950s,dysfunctio...",1980-03-07,124,PG,Michael Apted,Sissy Spacek,Tommy Lee Jones,...,120,58,24.7K,"$67,182,787",nan,https://www.imdb.com/title/tt0080549/,Old Movies,nan,67182787.0,NaN
40,Heaven&apos;s Gate,Adventure|Drama|Western,"During the Johnson County War in 1890 Wyoming,...","female full frontal nudity,cattle ranch,epic,s...",1981-04-24,219,R,Michael Cimino,Kris Kristofferson,Christopher Walken,...,298,103,31.2K,"$3,484,541","$44,000,000 (estimated)",https://www.imdb.com/title/tt0080855/,Old Movies,$,3484541.0,44000000.0

In [84]:
df[df['star_1'].str.contains(";")].head()

,title,genres,description,keywords,release_date,duration,content_rating,director,star_1,star_2,...,user_reviews,critic_reviews,watchlist_count,gross,budget,movie_url,category,currency_type,gross_usd,budget_usd
61,Scanners,Horror|Sci-Fi|Thriller,A scientist trains a man with an advanced tele...,"psychic power,exploding head,scientist,mall,sc...",1981-01-14,103,R,David Cronenberg,Jennifer O&apos;Neill,Stephen Lack,...,268,163,59.0K,"$14,225,876","CA$4,100,000 (estimated)",https://www.imdb.com/title/tt0081455/,Old Movies,CA$,14225876.0,3075000.0
69,The Stunt Man,Action|Comedy|Drama,"A fugitive hides on a film set, taking the pla...","on the run,brothel,female rear nudity,fugitive...",1980-06-27,131,R,Richard Rush,Peter O&apos;Toole,Steve Railsback,...,104,87,14.1K,"$7,063,886","$3,500,000 (estimated)",https://www.imdb.com/title/tt0081568/,Old Movies,$,7063886.0,3500000.0
132,Piranha Part Two: The Spawning,Horror|Sci-Fi|Thriller,"A scuba diving instructor, her biochemist boyf...","directorial debut,creature feature,scuba divin...",1982-08-14,94,R,James Cameron,Tricia O&apos;Neil,Steve Marachuk,...,112,112,7.4K,nan,"$145,786 (estimated)",https://www.imdb.com/title/tt0082910/,Old Movies,$,NaN,145786.0
190,My Favorite Year,Comedy|Drama,"An aging, dissolute matinee idol is slated to ...","womanizer,male bonding,chauffeur,stuffed anima...",1982-10-08,92,PG,Richard Benjamin,Peter O&apos;Toole,Mark Linn-Baker,...,104,35,10.5K,"$20,123,620","$7,900,000 (estimated)",https://www.imdb.com/title/tt0084370/,Old Movies,$,20123620.0,7900000.0
302,Balkanski spijun,Comedy|Drama,Convinced that his subtenant is a spy and an e...,"paranoia,reference to joseph stalin,twin broth...",1987-10-08,95,Unknown,Dusan Kovacevic,Danilo &apos;Bata&apos; Stojkovic,Bora Todorovic,...,22,2,10.6K,nan,nan,https://www.imdb.com/title/tt0086935/,Top Rated|Old Movies,nan,NaN,NaN

In [85]:
df[df['director'].str.contains(";")].head()

,title,genres,description,keywords,release_date,duration,content_rating,director,star_1,star_2,...,user_reviews,critic_reviews,watchlist_count,gross,budget,movie_url,category,currency_type,gross_usd,budget_usd
209,Tesna koza,Comedy,"In this light, fluffy comedy, a low-level cler...","female nudity,lawyer,clerk,wages,slacker",1982-09-24,92,Unknown,Milivoje &apos;Mica&apos; Milosevic,Nikola Simić,Milan &apos;Lane&apos; Gutovic,...,4,0,2.3K,nan,nan,https://www.imdb.com/title/tt0084780/,Top Rated,nan,NaN,NaN
459,The Return of the Living Dead,Comedy|Horror|Sci-Fi,When two bumbling employees at a medical suppl...,"living dead,naked dead woman,undead,zombie fil...",1985-08-16,91,R,Dan O&apos;Bannon,Clu Gulager,James Karen,...,438,169,54.2K,"$14,241,362","$4,000,000 (estimated)",https://www.imdb.com/title/tt0089907/,Old Movies,$,14241362.0,4000000.0
1093,Sweet November,Drama|Romance,"A workaholic executive, and an unconventional ...","san francisco california,terminal illness,rema...",2001-02-16,119,PG-13,Pat O&apos;Connor,Keanu Reeves,Charlize Theron,...,323,58,105K,"$65,754,228","$40,000,000 (estimated)",https://www.imdb.com/title/tt0230838/,Mid Rated,$,65754228.0,40000000.0
1095,BattleQueen 2020,Action|Sci-Fi,After a civilization is all but wiped out by a...,"female frontal nudity,lesbian,sex,nudity,botto...",2001-05-22,95,R,Daniel D&apos;Or,Julie Strain,Jeff Wincott,...,13,10,1.6K,nan,"CA$1,200,000 (estimated)",https://www.imdb.com/title/tt0232098/,Low Rated,CA$,NaN,900000.0
1422,Ella Enchanted,Comedy|Family|Fantasy,Ella is under a spell to be constantly obedien...,"fairy,prince,obedience,curse,racism",2004-04-09,96,PG,Tommy O&apos;Haver,Anne Hathaway,Hugh Dancy,...,301,79,78.5K,"$27,388,767","$31,000,000 (estimated)",https://www.imdb.com/title/tt0327679/,Mid Rated,$,27388767.0,31000000.0

In [86]:
import html

df['title'] = df['title'].apply(html.unescape)

df['star_1'] = df['star_1'].apply(html.unescape)
df['star_2'] = df['star_2'].apply(html.unescape)
df['star_3'] = df['star_3'].apply(html.unescape)

df['director'] = df['director'].apply(html.unescape)

In [87]:
df[df['title'].str.contains(";")].head()

Empty DataFrame
Columns: [title, genres, description, keywords, release_date, duration, content_rating, director, star_1, star_2, star_3, countries, languages, rating, metascore, votes, user_reviews, critic_reviews, watchlist_count, gross, budget, movie_url, category, currency_type, gross_usd, budget_usd]
Index: []

[0 rows x 26 columns]

In [88]:
df[df['star_1'].str.contains(";")].head()

Empty DataFrame
Columns: [title, genres, description, keywords, release_date, duration, content_rating, director, star_1, star_2, star_3, countries, languages, rating, metascore, votes, user_reviews, critic_reviews, watchlist_count, gross, budget, movie_url, category, currency_type, gross_usd, budget_usd]
Index: []

[0 rows x 26 columns]

In [89]:
df[df['director'].str.contains(";")].head()

Empty DataFrame
Columns: [title, genres, description, keywords, release_date, duration, content_rating, director, star_1, star_2, star_3, countries, languages, rating, metascore, votes, user_reviews, critic_reviews, watchlist_count, gross, budget, movie_url, category, currency_type, gross_usd, budget_usd]
Index: []

[0 rows x 26 columns]

In [91]:
# Stripping the text columns
df['genres'] = df['genres'].str.strip()
df['description'] = df['description'].str.strip()
df['keywords'] = df['keywords'].str.strip()
df['content_rating'] = df['content_rating'].str.strip()
df['star_1'] = df['star_1'].str.strip()
df['star_2'] = df['star_2'].str.strip()
df['star_3'] = df['star_3'].str.strip()
df['director'] = df['director'].str.strip()

In [92]:
df.head()

,title,genres,description,keywords,release_date,duration,content_rating,director,star_1,star_2,...,user_reviews,critic_reviews,watchlist_count,gross,budget,movie_url,category,currency_type,gross_usd,budget_usd
0,Kate & Leopold,Comedy|Fantasy|Romance,An English Duke from 1876 is inadvertently dra...,"time travel,time travel romance,female time tr...",2001-12-25,118,PG-13,James Mangold,Meg Ryan,Hugh Jackman,...,376,92,66.6K,"$76,019,048","$48,000,000 (estimated)",https://www.imdb.com/title/tt0035423/,Mid Rated,$,76019048.0,48000000.0
1,Ko to tamo peva,Adventure|Comedy|Drama,"It&apos;s April 5, 1941, somewhere in Serbia. ...","road trip,sex scene,female nudity,year 1941,yu...",1980-06-30,86,Unknown,Slobodan Sijan,Pavle Vuisic,Dragan Nikolic,...,42,11,12.2K,nan,nan,https://www.imdb.com/title/tt0076276/,Top Rated|Old Movies,nan,NaN,NaN
2,Cannibal Holocaust,Adventure|Horror,An anthropologist ventures into the Amazon rai...,"rape,animal cruelty,gang rape,actual animal ki...",1985-06-21,95,Unrated,Ruggero Deodato,Robert Kerman,Francesca Ciardi,...,685,208,66.8K,$477,"$100,000 (estimated)",https://www.imdb.com/title/tt0078935/,Old Movies,$,477.0,100000.0
3,Saturn 3,Adventure|Horror|Sci-Fi,Two lovers stationed at a remote base in the a...,"psychopath,infatuation,robot sci fi,male rear ...",1980-02-15,88,R,Stanley Donen,Farrah Fawcett,Kirk Douglas,...,165,63,9.3K,"$9,000,000","£10,000,000 (estimated)",https://www.imdb.com/title/tt0079285/,Old Movies,£,9000000.0,12500000.0
4,Moskva slezam ne verit,Comedy|Drama|Romance,Three young provincial women come to Moscow in...,"city name in title,group of friends,soviet uni...",1980-02-11,150,PG,Vladimir Menshov,Vera Alentova,Aleksey Batalov,...,56,13,14.6K,$217,"$900,000 (estimated)",https://www.imdb.com/title/tt0079579/,Old Movies,$,217.0,900000.0

In [19]:
df['category'].unique()

array(['Mid Rated', 'Top Rated|Old Movies', 'Old Movies', 'Top Rated',
       'Old Movies|Top Rated', 'Low Rated', 'Most Popular|Mid Rated',
       'Most Popular|Top Rated', 'Most Popular', 'Most Popular|Low Rated',
       'Mid Rated|Most Popular'], dtype=object)

---

## Testing Data Cleaning (2025 Movies)

<span style='font-size:18px;'>
    ➤ Cleaning the movies collected for testing the model. 
</span>

In [93]:
test_df = pd.read_csv('data/New_movies_data.csv')
test_df.head()

,title,genres,description,keywords,release_date,duration,content_rating,director,star_1,star_2,...,metascore,votes,user_reviews,critic_reviews,watchlist_count,gross,budget,opening_weekend,movie_url,category
0,Oficina do Diabo,Drama,An ambitious young demon is instructed by an o...,"supernatural drama,psychological drama",2025-01-12,124,NaN,Filipe Valerim,Roberto Mallet,Felipe de Barros,...,NaN,35126,132,NaN,7.4K,NaN,NaN,NaN,https://www.imdb.com/title/tt28459771/,New Movies
1,Mica è colpa mia,Comedy|Romance,"Drowning in debt, two brothers concoct a plan ...","naples italy,postman,man wears glasses,scam,be...",2025-01-01,101,NaN,Umberto Riccioni Carteni,Antonio Folletto,Laura Adriani,...,NaN,1745,9,17.0,1.1K,NaN,NaN,NaN,https://www.imdb.com/title/tt34896285/,New Movies
2,Meghalu Cheppina Prema Katha,Musical|Romance,Varun&apos;s musical journey intersects with M...,NaN,2025-08-22,143,NaN,Vipin,Radhika Sarathkumar,Tulasi,...,NaN,1051,NaN,NaN,NaN,NaN,NaN,NaN,https://www.imdb.com/title/tt37140876/,New Movies
3,Mathru,Thriller,"Serial kidnappings plague a town, each marked ...",NaN,2026-02-06,124,NaN,John Jakki,Aamani,Ravi Kale,...,NaN,1107,2,NaN,NaN,NaN,NaN,NaN,https://www.imdb.com/title/tt37803534/,New Movies
4,Viyaah Kartaare Da,NaN,A cunning but lazy man fakes his corrupt fathe...,NaN,2026-02-27,120,NaN,Smeep Kang,Gurpreet Ghuggi,Hardip Gill,...,NaN,1037,5,NaN,NaN,"$125,584",NaN,NaN,https://www.imdb.com/title/tt39875252/,New Movies

In [23]:
test_df.shape

(1, 24)

In [24]:
test_df.isna().sum()

title              0
genres             0
description        0
keywords           0
release_date       0
duration           0
content_rating     0
director           0
star_1             0
star_2             0
star_3             0
countries          0
languages          0
rating             0
metascore          0
votes              0
user_reviews       0
critic_reviews     0
watchlist_count    0
gross              0
budget             0
opening_weekend    0
movie_url          0
category           0
dtype: int64

In [96]:
test_df = test_df.dropna()

In [97]:
test_df.shape

(128, 24)

In [25]:
test_df.dtypes

title              object
genres             object
description        object
keywords           object
release_date       object
duration            int64
content_rating     object
director           object
star_1             object
star_2             object
star_3             object
countries          object
languages          object
rating              int64
metascore          object
votes               int64
user_reviews       object
critic_reviews     object
watchlist_count    object
gross              object
budget             object
opening_weekend    object
movie_url          object
category           object
dtype: object

In [26]:
test_df["release_date"] = pd.to_datetime(test_df["release_date"], errors="coerce")

In [27]:
import re
test_df['gross_usd'] = test_df['gross'].apply(convert_to_usd)
test_df["budget_usd"] = test_df["budget"].apply(convert_to_usd)

In [28]:
import html

test_df['title'] = test_df['title'].apply(html.unescape)

test_df['star_1'] = test_df['star_1'].apply(html.unescape)
test_df['star_1'] = test_df['star_1'].apply(html.unescape)
test_df['star_1'] = test_df['star_1'].apply(html.unescape)

test_df['director'] = test_df['director'].apply(html.unescape)

In [29]:
test_df = test_df.drop(columns=["opening_weekend"])

In [30]:
test_df['watchlist_count'] = test_df['watchlist_count'].apply(convert_to_number)
test_df['user_reviews'] = test_df['user_reviews'].apply(convert_to_number)
test_df['critic_reviews'] = test_df['critic_reviews'].apply(convert_to_number)

In [33]:
test_df.dtypes

title                      object
genres                     object
description                object
keywords                   object
release_date       datetime64[ns]
duration                    int64
content_rating             object
director                   object
star_1                     object
star_2                     object
star_3                     object
countries                  object
languages                  object
rating                      int64
metascore                 float64
votes                       int64
user_reviews              float64
critic_reviews            float64
watchlist_count           float64
gross                      object
budget                     object
movie_url                  object
category                   object
gross_usd                 float64
budget_usd                float64
dtype: object

In [90]:
test_df.head()

,title,genres,description,keywords,release_date,duration,content_rating,director,star_1,star_2,...,votes,user_reviews,critic_reviews,watchlist_count,gross,budget,movie_url,category,gross_usd,budget_usd
9,Nezha: Mo tong nao hai,Animation|Action|Adventure,"After a great catastrophe, the souls of Nezha ...","sequel,coco cartoon animated film,chinese folk...",2025-01-29,144,PG-13,Yu Yang,Yanting Lü,Joseph,...,23795,330.0,115.0,43800.0,"$2,260,176,370","$80,000,000 (estimated)",https://www.imdb.com/title/tt34956443/,New Movies,2.260176e+09,80000000.0
13,Him,Horror|Sport,A young athlete descends into a world of terro...,"american football sport,male rear nudity,male ...",2025-09-19,96,R,Justin Tipping,Marlon Wayans,Tyriq Withers,...,22039,381.0,139.0,46500.0,"$27,834,512","$27,000,000 (estimated)",https://www.imdb.com/title/tt20990442/,New Movies,2.783451e+07,27000000.0
14,They Will Kill You,Action|Comedy|Horror,A woman takes a job as a housekeeper in a NYC ...,"one person army action,splatter horror,occult ...",2026-03-27,94,R,Kirill Sokolov,Zazie Beetz,Myha&apos;la,...,5565,118.0,107.0,44000.0,"$10,421,707","$20,000,000 (estimated)",https://www.imdb.com/title/tt31728330/,New Movies,1.042171e+07,20000000.0
15,Return to Silent Hill,Drama|Horror|Mystery,When a man receives a mysterious letter from h...,"based on video game,male protagonist,psycholog...",2026-01-23,106,R,Christophe Gans,Jeremy Irvine,Hannah Emily Anderson,...,16572,469.0,98.0,48000.0,"$47,650,944","$23,000,000 (estimated)",https://www.imdb.com/title/tt22868010/,New Movies,4.765094e+07,23000000.0
18,One of Them Days,Comedy,When best friends and roommates Dreux and Alys...,"blood,african american,gun,los angeles califor...",2025-01-17,97,R,Lawrence Lamont,Keke Palmer,SZA,...,19176,126.0,73.0,31600.0,"$51,896,264","$14,000,000 (estimated)",https://www.imdb.com/title/tt32221196/,New Movies,5.189626e+07,14000000.0

---

## Saving Cleaned Dataset to CSV File

In [136]:
# Main cleaned Dataset
df.to_csv("data/IMDb_movies_cleaned.csv", index=False, encoding="utf-8")

In [34]:
test_df.to_csv("data/IMDb_test_movies_cleaned.csv", index=False, encoding="utf-8")

---